name: CyberChef Update
  
on:
  watch:
    types: [started]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * MON'

jobs:
  CyberChef_Update:
    name: CyberChef Update
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0
      - 
        name: Create local changes
        run: |
          rm -rf *
          wget -O CyberChef.zip `curl -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.TOKEN_GITHUB }} -s https://api.github.com/repos/gchq/CyberChef/releases/latest | grep "browser_download_url" | cut -d '"' -f 4`
          unzip CyberChef.zip
          mv CyberChef_*.html index.html
          rm CyberChef.zip
      - 
        name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes by CyberChef_Update_Action" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: ${{ github.ref }}